### ISSUE TITLE
Flag for #[link = "..."] Attribute

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust-bindgen#1358]
It'd be nice if the bindgen CLI had an arg that would allow setting the name of the library to be linked against, which would then be emitted as `#[link = "<somename>"]` attributes. I'd be happy to try my hand at a PR for this if it's wanted.

**Comment by emilio** [comment]
I'm not opposed to this if there's demand for this... It'd be nice to know what people use `--raw-line` for :).

But I also wouldn't want bindgen to end up with even more options for niche use cases. links have different kinds and we'd need to expose a flexible enough API, which is why I ended up removing the (already-useless because I forgot about them when rewriting bindgen) options in #104.

In any case, fine getting them back if it's a very frequent thing to do. Though given not so many people ended up caring about #104 I doubt it's the case.

**Comment by cramertj** [comment]
> In any case, fine getting them back if it's a very frequent thing to do. Though given not so many people ended up caring about #104 I doubt it's the case.

@emilio Do you figure most people are adding the link declarations via a build script, or are they just already including them elsewhere in their projects?

**Comment by emilio** [comment]
I don't know at all. I assume for build scripts you can `println!("cargo:rustc-link-lib=foo")` on your `build.rs`, and for CLI usage people drop the link attributes in some other part of the project or what not.

**Comment by LegNeato** [comment]
I am trying to statically link (`kind = "static"`) and the generated default appears to be dynamic. This will be nice to have but in the meantime I'll use `println!("cargo:rustc-link-lib=foo")`
