### ISSUE TITLE
Copy not derived when using whitelist_recursively(false)

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust-bindgen#1454]
### Input C/C++ Header

```C++
#include <stdint.h>
#include <stdlib.h>
typedef uint64_t mbedtls_mpi_uint;
typedef struct
{
    int s;              /*!<  integer sign      */
    size_t n;           /*!<  total # of limbs  */
    mbedtls_mpi_uint *p;          /*!<  pointer to limbs  */
}
mbedtls_mpi;
```

### Bindgen Invocation

```Rust
    let bindings = bindgen::builder()
        .header_contents("test.h", ...)
        .trust_clang_mangling(false)
        .derive_copy(true)
        .whitelist_type("mbedtls_.*")
        .whitelist_recursively(whitelist_recursively)
        .layout_tests(false)
        .generate()
        .expect("bindgen error");
```

### Actual Results

```rust
// whitelist_recursively = false
/* automatically generated by rust-bindgen */

pub type mbedtls_mpi_uint = u64;
#[repr(C)]
pub struct mbedtls_mpi {
    ///<  integer sign
    pub s: ::std::os::raw::c_int,
    ///<  total # of limbs
    pub n: usize,
    ///<  pointer to limbs
    pub p: *mut mbedtls_mpi_uint,
}
```

### Expected Results

```Rust
// whitelist_recursively = true
/* automatically generated by rust-bindgen */

pub type mbedtls_mpi_uint = u64;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mbedtls_mpi {
    ///<  integer sign
    pub s: ::std::os::raw::c_int,
    ///<  total # of limbs
    pub n: usize,
    ///<  pointer to limbs
    pub p: *mut mbedtls_mpi_uint,
}
```

**Comment by emilio** [comment]
So what's going on is that when not whitelisting recursively we're not seeing through the built-in types (since they're not whitelisted!) and then we think we cannot derive stuff for them. You can see this if you do `whitelist_type(".*")` where the result is the expected one.

I think we could auto-whitelist items that don't generate code to make this better.

**Comment by emilio** [comment]
https://github.com/rust-lang/rust-bindgen/pull/1492 should address this. You should also whitelist `size_t|uint64_t` on your test-case, since bindgen thinks it's an alias.

We could do the check of whether we're a known alias there as well, which would be more convenient too, though a bit more code and another list that we need to make sure doesn't go out of sync.

Thoughts @jethrogb? Does that patch would work for you?

**Comment by jethrogb** [comment]
Can we do something like *if* the non-whitelisted types of member fields were emitted *and* that would result in the particular derive, *then* we do the derive anyway without emitting the member type?

**Comment by jethrogb** [comment]
Please reopen
