### ISSUE TITLE
use winapi crate instead of generating bindings to windows.h

### ISSUE THREAD

**Issue by oezgurmakkurt** [rust-lang/rust-bindgen#1562]
Hi, I couln't find any way to do this in docs or the book, I am generating bindings to vulkan but when I add a definition to make it include windows support It includes windows.h, build takes a long time and it crashes with no output. I want to ignore the windows.h include somehow and use winapi crate instead. Is there a way to this?

**Comment by emilio** [comment]
The way to do something like that is to blacklist the windows types and adding something like `use winapi::*` using `raw_line`.

Bindgen shouldn't be crashing though (and it's somewhat suprising it does since I'm pretty sure on Firefox bindgen ends up including windows.h without issues).

I don't have a windows machine, but would there be any chance for you to try to [dump the contents make bindgen crash for you](https://github.com/rust-lang/rust-bindgen/blob/master/CONTRIBUTING.md#isolating-your-test-case) and upload them here?

A reduced test-case would be extra-awesome, but just a reproducible crash / hang is awesome on its own.

**Comment by oezgurmakkurt** [comment]
hi, bindgen doesn't crash but I get this error when compiling the generated bindings: error[E0588]: packed type cannot transitively contain a `[repr(align)]` type. the generated rust file is 1 line so the error was too long, thats why I couldn't see anything. so I think this is duplıcate of #1538.

**Comment by emilio** [comment]
Yeah, with_rustfmt and such helps a lot to diagnose errors :)

**Comment by bugproof** [comment]
Why was this issue closed?

**Comment by kulp** [comment]
> Why was this issue closed? IMO there should be a switch like `--use-winapi`

The original author [came to believe](https://github.com/rust-lang/rust-bindgen/issues/1562#issuecomment-493526443) the underlying issue is a duplicate of another open issue.

@bugproof, if you have a need, maybe you should open a new issue to describe what use you would have for `--use-winapi`.

**Comment by sam0x17** [comment]
I have the same problem. Was there ever a solution?

**Comment by sam0x17** [comment]
followup: Looks like if you blacklist the following types build will succeed with all of windows.h:

```
        .blacklist_type("_IMAGE_TLS_DIRECTORY64")
        .blacklist_type("IMAGE_TLS_DIRECTORY64")
        .blacklist_type("PIMAGE_TLS_DIRECTORY64")
        .blacklist_type("IMAGE_TLS_DIRECTORY")
        .blacklist_type("PIMAGE_TLS_DIRECTORY")
```

**Comment by IoIxD** [comment]
Hey, can somebody here answer the original question a bit better?

How am I supposed to "blacklist the windows types"? I tried blocklisting windows.h and that doesn't work. I was suggested to use regex to filter out all the functions, but Microsoft uses hungarian notation so that doesn't work.
