### ISSUE TITLE
Add a cargo feature to disable rustfmt

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust-bindgen#1614]
I never `rustfmt` generated bindings and I do not check them into source control.

rustfmt'ing brings in a dependency on which -> failure -> backtrace that I otherwise do not need.

Can we add a cargo feature to disable `rustfmt`ing of code and make the `which` crate an optional dependency?

**Comment by emilio** [comment]
Yeah, that seems pretty reasonable. Given rustfmt'ing is a best-effort thing anyway it may be worth not touching the public API and just early-return from the rustfmt path.

It may be worth rather than a feature to disabling rustfmt, adding a default-feature enable auto-finding rustfmt (and thus `which`), but still allow to run rustfmt via the env variable or what explicit option if appropriate, that is, basically, adding a feature called `which` or something, then cfg-ing this `match` out based on that and returning an error directly:

https://github.com/rust-lang/rust-bindgen/blob/ac99aa14097aaa7cf09e8f9cf74449d2f84de155/src/lib.rs#L1911

That allows to run rustfmt if explicitly asked for it and skip the which dependency. Are you ok with this @lopopolo? Would you be willing to send a patch for that?

**Comment by lopopolo** [comment]
@emilio I’d be happy to pick this up. I am headed out on vacation tomorrow though so it may be a couple of weeks.

**Comment by lopopolo** [comment]
I had some time today and this was easier than I expected so I got the PR put together 😄
