### ISSUE TITLE
Can't bind to char * generated variable correctly

### ISSUE THREAD

**Issue by xky0007** [rust-lang/rust-bindgen#1825]
### Input C/C++ Header

```C
int add(int, int);
int swap(int, int);
typedef struct Person
{
    char *name;
    int id;
} Person;

void print(Person *);
```
### Bindgen Invocation

```
$ bindgen input.h -o bin.rs
```

### Source Code
```
extern crate dlopen;

#[macro_use]
extern crate dlopen_derive;
use dlopen::wrapper::{Container, WrapperApi};

#[derive(WrapperApi)]
struct Api {
    add: fn(arg: i32, b: i32) -> i32,
    swap:fn(a:i32, b:i32) -> i32,
    // example_reference: &'a mut i32,
    print:fn(p:*mut bin::Person)
}

fn main(){
    let mut cont: Container<Api> =
        unsafe { Container::load(".\\src\\my-math.dll") }.expect("Could not open library or load symbols");
    let r = cont.add(5,6);

    let p1:*mut bin::Person =&mut *Box::new( bin::Person{
        name:String::from("hhh ").as_mut_ptr(),
        id:991
    });
    println!("{}",r);
    println!("{}",cont.swap(66,99));
    cont.print(p1);
}
```
`add()` and `swap()` functions are working correctly but `print()` name generate random unknown output like `Id:991 Nameqy?`.
The correct result should be `Id:991 Name:hhh`.

What is the correct way to binding `char *` in C?

**Comment by emilio** [comment]
`String::from("hhh ").as_mut_ptr()` -> That is a use after free. You're taking the pointer to a heap object that gets deallocated right after because it's a temporary. Also, the string needs to be null-terminated so you're always going to get garbage.

If `Person` isn't meant to own the chars, you can use `const char*` and then something like `b"hhh \0".as_ptr()`. Or if the string is dynamic you can use `std::ffi::CString` or `std::ffi::CStr`.

If person is meant to own the chars (and thus responsible for freeing them) you can use something like:

```
let bytes = CString::new("hhh ").unwrap().into_bytes_with_nul();
let mut person = bin::Person {
   name: bytes.as_mut_ptr(),
   id: 991,
};
std::mem::forget(bytes); // `person` owns the bytes now.
cont.print(person);
// Something would need to free the name after
```

Depending on whether the
