### ISSUE TITLE
Complex C++ template causes invalid Bindgen output

### ISSUE THREAD

**Issue by talbenari1** [rust-lang/rust-bindgen#1837]
This is quite difficult to explain without an example, so here's a super-contrived header:
```cpp
template <typename T, T init>
struct Foo {
  const static T value = init;
};

template <typename T, T init>
const T Foo<T, init>::value;
```
Bindgen has no problems generating the bindings for this header file, but the output looks like this:
```rust
/* automatically generated by rust-bindgen */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    extern "C" {
        pub static value: T;
    }
}
```
The error when trying to compile the generated Rust bindings is ``error[E0412]: cannot find type `T` in this scope``, which should be fairly clear from the output above.

Note: I found this after lots of debugging and trial-and-error; ultimately the problem was located in the `<type_traits>` system header file on my machine. You might be able to reproduce this, like I did, simply via `#include <type_traits>`.

**Comment by emilio** [comment]
Thanks for the reduced test-case. I think this the same as https://github.com/rust-lang/rust-bindgen/issues/1838. We could probably dupe any against each other, but I went in LIFO order so that one has already the tags :) 

Fwiw, I don't think this would be hard to fix, we probably just need a template check either when scanning constants or when generating them.
