### ISSUE TITLE
Multidimensional array binding has incorrect mutability.

### ISSUE THREAD

**Issue by jbangelo** [rust-lang/rust-bindgen#1849]
### Input C/C++ Header

```C
void foo(const int array[][5]);
```

### Bindgen Invocation
Using `bindgen` execute version 0.54.1

```
$ bindgen array_func.h
```

### Actual Results

```rust
extern "C" {
    pub fn foo(array: *mut [::std::os::raw::c_int; 5usize]);
}
```

### Expected Results
```rust
extern "C" {
    pub fn foo(array: *const [::std::os::raw::c_int; 5usize]);
}
```

The pointer in the bindings should not be mutable. In the C function the `const` applies to all dimensions of the array, and there's no way to legally modify any part of the array. A single dimension array works as expected, so it seems to be just an issue with multidimensional arrays.

**Comment by jbangelo** [comment]
I'd be happy to help resolve this issue, assuming it is indeed a real problem. Pointers/suggestions on where or how to fix this would be appreciated (sorry about the pun 😄).

**Comment by emilio** [comment]
Hmm, I'd look at similar issues like #1727 and such. https://github.com/rust-lang/rust-bindgen/commit/e09602bb8ba690c0caf317c7eb9fe4462a68bd84 is the fix for that, maybe we're missing a similar check in the code that parses arrays. Though I'd first double-check that that is what the C compiler is doing.

Thanks for filing this!
