### ISSUE TITLE
Unable to compile bindgen libraries for ESP32 

### ISSUE THREAD

**Issue by fmc5046** [rust-lang/rust-bindgen#1853]
### Actual Results

```rust
          /home/fred/xtensa-rust-quickstart/target/xtensa-esp32-none-elf/debug/deps/esp32-8ad70c7d5337caba.esp32.66tnvxh8-cgu.0.rcgu.o:(.literal.main+0x14): undefined reference to `uart_param_config'
          /home/fred/xtensa-rust-quickstart/target/xtensa-esp32-none-elf/debug/deps/esp32-8ad70c7d5337caba.esp32.66tnvxh8-cgu.0.rcgu.o:(.literal.main+0x18): undefined reference to `uart_set_pin'
          /home/fred/xtensa-rust-quickstart/target/xtensa-esp32-none-elf/debug/deps/esp32-8ad70c7d5337caba.esp32.66tnvxh8-cgu.0.rcgu.o:(.literal.main+0x20): undefined reference to `uart_driver_install'
          /home/fred/xtensa-rust-quickstart/target/xtensa-esp32-none-elf/debug/deps/esp32-8ad70c7d5337caba.esp32.66tnvxh8-cgu.0.rcgu.o:(.literal.main+0x3c): undefined reference to `uart_write_bytes'
          collect2: error: ld returned 1 exit status

```
### Expected Results

Hi I'm using bindgen libraries generated to use peripheral functions, such as printing to the serial bus for the ESP32 board and I'm getting the error above when compiling with xargo build.  Any ideas as to what would prevent it from seeing the .h file that has the functions defined? 

The library is from the following location: https://github.com/lexxvir/esp32-hello

When I try to build the original repo I get the following error, Im not sure if they are related

### Actual Results from Original repo

```rust
/home/fred/esp/xtensa-esp32-elf/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: cannot open linker script file esp32_out.ld: No such file or directory
          collect2: error: ld returned 1 exit status


```

When I don't include the binding files I am able to compile and flash

**Comment by emilio** [comment]
So those are all linker errors, which means that rustc is calling functions that are not defined in the final binary.

You need to figure out where are those symbols supposed to be defined, but bindgen doesn't take care of linking or anything like that, so I suspect the error is somewhere else.

**Comment by emilio** [comment]
If you don't call the functions, then you don't get the linker errors, but that is expected, because rustc doesn't end up calling them. The second error may be related in the sense that it's a linker script that could potentially define those functions.

I think you should file an issue in https://github.com/MabezDev/xtensa-rust-quickstart instead, I don't think this is actionable from bindgen. Bindgen is just a text-to-text tool effectively, and seems to be working fine in your example.

But let me know if you disagree, or there's something we could improve here, and reopen if so. Thank you!
