### ISSUE TITLE
Unclear whether or not `libloading` wrapper struct should have publicly accessible fields

### ISSUE THREAD

**Issue by Cldfire** [rust-lang/rust-bindgen#1937]
#1931 changed the visibility of all the function pointer fields in the generated `libloading` wrapper struct from private to public.

However, in https://github.com/rust-lang/rust-bindgen/pull/1846#issuecomment-692425348, a convincing argument was made that these fields should remain private for safety reasons.

#1931 doesn't seem to discuss the safety concerns; I'm just wondering what the thought process was there :slightly_smiling_face:

**Comment by emilio** [comment]
This was intentional. The main reason is that:

 * If you don't do this then we can't call varargs functions at all.
 * It complicated the code having to add an extra wrapper struct just to check if a function was correctly loaded.

Calling the public version of the symbol and grabbing a reference to it that outlives the `Library` is unsafe, so users are at their own risk if using that, and I think that's fine, but let me know if you disagree.
