### ISSUE TITLE
Macro constant referencing an enumerator does not generate a Rust constant

### ISSUE THREAD

**Issue by doctortheemh** [rust-lang/rust-bindgen#2192]
Hi all. I'm working on an issue with [ffmpeg-next](https://crates.io/crates/ffmpeg-next) and [ffmpeg-sys-next](https://crates.io/crates/ffmpeg-sys-next), which are rust bindings to ffmpeg. I'm seeing build errors for former crate on macos stemming from missing constants in the generated bindings. Curiously, linux does not seem to have this issue. I whittled down a smaller test case I believe represents the problem, however, both Linux and macos bindgen invocations are now producing the same results. I'm a bit at loss, can anyone advise if the behavior I'm seeing from bindgen makes sense?

### Input C/C++ Header

```
enum AVChannel {
    AV_CHAN_NONE = -1,
    AV_CHAN_FRONT_LEFT,
};

#define AV_CH_FRONT_LEFT             (1ULL << AV_CHAN_FRONT_LEFT           )
```

### Bindgen Invocation

```
$ bindgen test.h
```

### Actual Results

```rust
/* automatically generated by rust-bindgen 0.59.2 */

pub const AVChannel_AV_CHAN_NONE: AVChannel = -1;
pub const AVChannel_AV_CHAN_FRONT_LEFT: AVChannel = 0;
pub type AVChannel = ::std::os::raw::c_int;
```

### Expected Results

I'd expect to see a constant for AV_CH_FRONT_LEFT.

**Comment by kulp** [comment]
> Curiously, linux does not seem to have this issue.

I am able to reproduce the issue both on macOS and on FreeBSD (I have no Linux hosts immediately available). If you can give evidence of platform-dependency, that would be interesting.

I think this is another case like #316 or #753. The desired `AV_CH_FRONT_LEFT` constant appears, if the definition is changed to avoid the reference to the `AV_CHAN_FRONT_LEFT`:
```diff
-#define AV_CH_FRONT_LEFT             (1ULL << AV_CHAN_FRONT_LEFT           )
+#define AV_CH_FRONT_LEFT             (1ULL << 0                            )
```

It would not be terribly surprising if `bindgen` cannot interpolate `enum`s into macros, since `bindgen` would have to provide the enum values somehow to `rust-cexpr`'s macro evaluation. If you want to look at something concrete, you might be able to estimate how feasible it would be for that to be done.

I do not have a concrete recommendation for you, besides manually coding the constant in your code; maybe @emilio would have one.

**Comment by kulp** [comment]
Sorry to say, I discovered this is a duplicate of a very old issue: #258.
