### ISSUE TITLE
`const T some_array[];` is compiled as `static mut some_array: [T; 0usize];`, which seems wrong.

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust-bindgen#2290]
For some reason, a C header containing a declaration like:
```c
extern const char some_static_string[];
```

is compiled to a rust bindings file with the following declaration:

```rs
extern "C" {
    pub static mut some_static_string: [::std::os::raw::c_char; 0usize];
}
```

This is wrong for a few reasons:
1. It's `static mut`, even though the input is a constant (in readonly memory, even).
2. It may be UB to read past the end (possibly even if done carefully with something `core::ptr::addr_of!` or similar): See <https://github.com/rust-lang/unsafe-code-guidelines/issues/259>.

In theory the second might be a bigger problem (since maybe it would cause the symbol not to point at the right thing), but in practice it doesn't seem like anything goes wrong. And I have no suggestion for an alternative.

The first is less subtle, and has a more obvious fix (ditch the `mut`), so it's probably worth fixing. That said, it's probably harmless (so long as you never write to it... which requires `unsafe` anyway).

**Comment by pvdrz** [comment]
So this basically happens because clang is not able to evaluate `some_static_string` due to being external and at the same time `clang_isConstQualifiedType` returns false (not sure why though). This seems like a similar instance of https://github.com/rust-lang/rust-bindgen/issues/1727 so maybe we should special case incomplete arrays too.
