### ISSUE TITLE
Release 1.0 or don't rev patches.

### ISSUE THREAD

**Issue by nsabovic** [rust-lang/rust-bindgen#2665]
When using pre-1.0 (`0.x.y`) versions, cargo versioning says that specifying `0.66.1` makes `0.67.0` incompatible. In other words, change from `0.68.0` to `0.69.0` is treated just like change from `1.0.0` to `2.0.0`. This means that when five crates use `bindgen`, odds are that they will each compile and use a different version of `bindgen`. It also means that crates using, say `0.59.0`, which work just fine with `0.68.0` won't be able to use it, for, say, cross-compiling. Which is what brought me here.

The last few releases did not have any breaking changes, nothing removed or changed in the user-facing API. One solution is to not roll out minor versions unless they are actually incompatible changes and just keep making patch releases.

`bindgen` is used by a majority of -sys crates so safe to say, it's not going to be radically changed in near future. Probably the right solution is to release the 1.0 version.

And celebrate!

**Comment by pvdrz** [comment]
Hi, thanks for filling this issue. I have some comments about your request:

> The last few releases did not have any breaking changes, nothing removed or changed in the user-facing API.

This is not true, in the [changelog](https://github.com/rust-lang/rust-bindgen/blob/main/CHANGELOG.md) there are at least 4 changes in` 0.68.0` that are breaking changes. This release is no exception, the next release of bindgen will remove a public constant which is a breaking change, 0.66 changed the type of non-utf-8 string constants and removed features from the manifest, 0.65 removed a bunch of deprecated flags, etc.

> One solution is to not roll out minor versions unless they are actually incompatible changes and just keep making patch releases.

This is something that we already do (as far as I'm aware), it just happen to be the case that most people won't request a new release until a breaking change they need is implemented but not released.

> `bindgen` is used by a majority of -sys crates so safe to say, it's not going to be radically changed in near future. Probably the right solution is to release the 1.0 version.

If we release 1.0 we would  be basically having the same problem you mentioned here

> When using pre-1.0 (`0.x.y`) versions, cargo versioning says that specifying `0.66.1` makes `0.67.0` incompatible. In other words, change from `0.68.0` to `0.69.0` is treated just like change from `1.0.0` to `2.0.0`. This means that when five crates use `bindgen`, odds are that they will each compile and use a different version of `bindgen`. It also means that crates using, say `0.59.0`, which work just fine with `0.68.0` won't be able to use it, for, say, cross-compiling. Which is what brought me here.

but with major releases instead of pre-1.0 minor releases, e.g one crate uses bindgen `1.0` and another crate uses bindgen `2.0` and you'd have to download each version individually to compile your project.

**Comment by nsabovic** [comment]
Thank you taking the time for such a thoughtful response.

All valid points. I guess the only salient one is what is the impact of the changes. I admit I haven't run [crater](https://github.com/rust-lang/crater) to see if the symbol that was removed was actually used by anyone. I guess my experience is anecdotal in that I haven't seen any breakage in the wild but I have such a limited view compared to what you see. If you are seeing actual breakages in the dependencies, then by all means keep reving. I will close this bug.
