### ISSUE TITLE
Option for only generating bindings for filenames matching a pattern

### ISSUE THREAD

**Issue by crumblingstatue** [rust-lang/rust-bindgen#303]
[Yamakaky/rust-bindgen](https://github.com/Yamakaky/rust-bindgen) has [this option](https://github.com/Yamakaky/rust-bindgen/blob/da4ecea3da8fab3b36d62d79e1f0cc2367c629f9/src/main.rs#L30-L33), which allows only generating bindings for filenames matching a pattern.

I make use of this feature for [rust-sfml](https://github.com/jeremyletang/rust-sfml), where there are [multiple auto-generated bindings that depend on each other](https://github.com/jeremyletang/rust-sfml/blob/ba02f79e55ce6efaa378d2f0e98409634df949cf/csfml-graphics-sys/src/lib.rs#L6-L10), so I don't want to regenerate all the bindings for each library.

I'm trying out servo/rust-bindgen because Yamakaky/rust-bindgen is [broken with Clang 3.9](https://github.com/Yamakaky/rust-bindgen/issues/400), but I cannot make the switch without this feature.

**Comment by emilio** [comment]
So the idea was replacing that `--matches` flag, which is particularly tricky (stuff can be declared in multiple files, also in C++), with the `--whitelist` flags.

Note that, even though it's not too well documented, the `--whitelist` flags accept a regex, so for sfml-audio-sys you could do something like `--whitelist-type "sfMusic.*" --whitelist-type "sfSound.*" --whitelist-function "sfSound.*" ...`.

If your functions depend on other, you can explicitly blacklist the types that depend on other libraries and use other flags for the imports.

This is relatively hard for sfml because as you said there are a lot of inter-dependencies. Let me know if the white/blacklisting approach works for you.

I can try to implement `--matches` looking for the definition of stuff, but it can be relatively tricky with a bunch of things that clang doesn't expose.

For the record what the Yamakaky's bindgen does is just not parse the rest of files, which is easy, but it's also a source of internal problems inside that bindgen that we don't have to deal with (that kind of stuff is what made me do #37).

**Comment by crumblingstatue** [comment]
I find constructing a whitelist manually too tedious to deal with. Especially since I was spoiled by `--matches`, and it works without problems for rust-sfml.

**Comment by pvdrz** [comment]
This was fixed when `Builder::allowlisted_files` was introduced.
